.PHONY: clean All

All:
	@echo "----------Building project:[ jump - Debug ]----------"
	@cd "jump" && "$(MAKE)" -f  "jump.mk" && "$(MAKE)" -f  "jump.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ jump - Debug ]----------"
	@cd "jump" && "$(MAKE)" -f  "jump.mk" clean
