.PHONY: clean All

All:
	@echo "----------Building project:[ VariousTextString - Debug ]----------"
	@cd "VariousTextString" && "$(MAKE)" -f  "VariousTextString.mk"
clean:
	@echo "----------Cleaning project:[ VariousTextString - Debug ]----------"
	@cd "VariousTextString" && "$(MAKE)" -f  "VariousTextString.mk" clean
