.PHONY: clean All

All:
	@echo "----------Building project:[ 5-3 - Debug ]----------"
	@cd "5-3" && "$(MAKE)" -f  "5-3.mk" && "$(MAKE)" -f  "5-3.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ 5-3 - Debug ]----------"
	@cd "5-3" && "$(MAKE)" -f  "5-3.mk" clean
