.PHONY: clean All

All:
	@echo "----------Building project:[ mop3-5 - Debug ]----------"
	@cd "mop3-5" && "$(MAKE)" -f  "mop3-5.mk" && "$(MAKE)" -f  "mop3-5.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ mop3-5 - Debug ]----------"
	@cd "mop3-5" && "$(MAKE)" -f  "mop3-5.mk" clean
