.PHONY: clean All

All:
	@echo "----------Building project:[ libMD407 - Debug ]----------"
	@cd "libMD407" && "$(MAKE)" -f  "libMD407.mk" && "$(MAKE)" -f  "libMD407.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ libMD407 - Debug ]----------"
	@cd "libMD407" && "$(MAKE)" -f  "libMD407.mk" clean
