.PHONY: clean All

All:
	@echo "----------Building project:[ lektion10 - Debug ]----------"
	@cd "lektion10" && "$(MAKE)" -f  "lektion10.mk" && "$(MAKE)" -f  "lektion10.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ lektion10 - Debug ]----------"
	@cd "lektion10" && "$(MAKE)" -f  "lektion10.mk" clean
